meta_product_name: "Lucid Guide"
meta_title: "Lucid Guide - Find the City that matches You"
meta_description: "Smart City Comparison showing only what is relevant for you"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
